// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD75Ro49A4NcSxkvKXxS0wZb2EnScsYPQ8',
    appId: '1:1067323170917:web:f239b292e9467d615da68c',
    messagingSenderId: '1067323170917',
    projectId: 'uniube-gerenciador-tarefas',
    authDomain: 'uniube-gerenciador-tarefas.firebaseapp.com',
    storageBucket: 'uniube-gerenciador-tarefas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlCwitQopQp7tSxWgv7uaHVnAVvD7u5c',
    appId: '1:1067323170917:android:ecbbf8b38a174da05da68c',
    messagingSenderId: '1067323170917',
    projectId: 'uniube-gerenciador-tarefas',
    storageBucket: 'uniube-gerenciador-tarefas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfel2fRjMWnt1RpX_2a2h_YKQpmz6nknk',
    appId: '1:1067323170917:ios:905e0d5a9e45e2845da68c',
    messagingSenderId: '1067323170917',
    projectId: 'uniube-gerenciador-tarefas',
    storageBucket: 'uniube-gerenciador-tarefas.firebasestorage.app',
    iosBundleId: 'com.ceciliamelo.gerenciadorTarefas',
  );
}
